dist: xenial   # required for Python >= 3.7
language: python
python:
  # CPython
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  # PyPy
  - "pypy3.5"
# command to install dependencies
install:
  - pip install pytest
# command to run tests
script:
  - pytest test_cls
