dist: xenial
language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
- pypy3.5
install:
- pip install -U pytest codecov pytest-cov
- pip install .
script:
- pytest --cov=./ test_cls
after_success:
- codecov
deploy:
  provider: pypi
  user: guoquan
  password:
    secure: UZzIVAPy9jUdpgCo2VJjrh+y2D6lRXcVAEAG8tl9zJ8f+fF5iHJjHxCzJ+dA0PFyZvJdYPxdocB9ILFW7daFSwsX5V2l0OjNQtMS6EbzjTLZWOwjTbaa3zif3C9mxTz+hYu9Bfy1kNLAEmvsGX+TvI3lJCuaD3iysPuP12vEkYKq9+d2MEoQlIfse/kdT5uGLm37CLDuIWrK9orvk15VW6Dj4bHEePQtX9lrGiDR7kZC78K4n39JrnadYjQkBzRae2SwntANCKAGBLo/OV7Wqd3tE9gXE0VNYLqTLaXg9BzGELb49Ev70pk7TSAvQgAfrylr81PFPJmPg7amc/dtLDqAWCuhSZLIDCF54oSwsHdxqbZhb6gLmRJ5P4Xg4WF3X1BebPsLhyjOFVJzZfrGmElitlryCBASyPdGKsDsIiH9zmZy8r5zp/mmDM8QQ+JJnEWroQnjkfto+R4UUk0InjgyxWdCN5ZqDewsU20on//moHZR8hG4HZNwOo9ieN28LzH6JHqKNYWaFE9AX/DpZgYGFspX8O3HEsoebDSxNDQ5yYSukt0CQMzT6HE2EQf072J9iJcoe+XErpmOd9PhXN29E96vTpvSsIFOswbpDiR7x4Hdt1lt3Y6Uaiv6/8VdOz1Gf78OMQq6OimDAwsS3qgESMAmLxql5g8B/rOU+cc=
