language: python
python:
  # CPython
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy
  - "pypy3.3"
  - "pypy3.4"
  - "pypy3.5"
  - "pypy3.6"
  - "pypy3.7"
# command to install dependencies
install:
  - pip install pytest
# command to run tests
script:
  - pytest test_cls
