version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Update PATH
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - checkout
      - run: mkdir .pip_cache
      - restore_cache:
          keys:
            #- pip-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "requirements.txt" }}
            - pip-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-
            - pip-{{ .Branch }}-
            - pip-
      - run:
          name: install python dependencies
          command: |
            pip install --user --cache-dir .pip_cache pytest
            if [ -e requirements.txt ]; then pip install --user --cache-dir .pip_cache -r requirements.txt; fi
      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "requirements.txt" }}
          paths:
            - ".pip_cache"
      - run: pytest test_cls

workflows:
  version: 2
  build_test:
    jobs:
      - test
